//! `cargo rubric trace`: render the traceability matrix as markdown.
//!
//! A self-contained artifact for an evidence package. Reflects the
//! current scan; the Status column folds in the oracle's verdict, so a
//! drifted or incomplete chain is visible in the matrix itself.

use std::collections::BTreeMap;
use std::path::Path;
use std::process::ExitCode;

use rubric_trace::check::{self, Citation, Direction, Finding, Scan, STATEMENT_MARKER};
use rubric_trace::lock::Origin;
use rubric_trace::manifest::{Kind, Manifest};

use crate::members;
use crate::project;

pub fn run() -> ExitCode {
    members::drive(trace_one)
}

fn trace_one(root: &Path, label: Option<&str>) -> Result<bool, String> {
    let p = project::load(root)?;
    let report = check::check(&p.manifest, &p.lock, &p.scan);
    print!("{}", render(&p.manifest, &p.scan, &report, label));
    // `trace` is a report, not a gate: it always succeeds.
    Ok(true)
}

fn render(manifest: &Manifest, scan: &Scan, report: &check::Report, member: Option<&str>) -> String {
    // Short status reasons per requirement, plus orphan annotations.
    let mut reasons: BTreeMap<&str, Vec<String>> = BTreeMap::new();
    let mut orphans: Vec<(&str, &str)> = Vec::new();
    for f in &report.findings {
        match status_reason(f) {
            Reason::Req(label, text) => reasons.entry(label).or_default().push(text),
            Reason::Orphan(label, item) => orphans.push((label, item)),
        }
    }

    let mut out = String::new();
    match member {
        Some(m) => out.push_str(&format!("# Traceability matrix — {m}\n\n")),
        None => out.push_str("# Traceability matrix\n\n"),
    }
    out.push_str("Generated by `cargo rubric trace`.\n\n");
    out.push_str("| Requirement | Kind | Statement | Satisfied by | Verified by | Status |\n");
    out.push_str("|---|---|---|---|---|---|\n");

    for req in &manifest.requirements {
        let sat = cells(scan, &req.label, Direction::Satisfies);
        let ver = cells(scan, &req.label, Direction::Verifies);

        let sat_cell = match (req.kind, sat.is_empty()) {
            (Kind::Invariant, true) => "—".to_string(),
            (Kind::Functional, true) => "**missing**".to_string(),
            (_, false) => sat.join("<br>"),
        };
        let ver_cell = if ver.is_empty() { "**missing**".to_string() } else { ver.join("<br>") };

        let status = match reasons.get(req.label.as_str()) {
            None => "✓ sealed".to_string(),
            Some(rs) => format!("✗ {}", rs.join("; ")),
        };

        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} |\n",
            req.label,
            kind_str(req.kind),
            escape(&req.statement),
            sat_cell,
            ver_cell,
            status,
        ));
    }

    if !orphans.is_empty() {
        out.push_str("\n## Orphan annotations\n\n");
        out.push_str("Annotations citing a requirement not defined in `rubric.toml`:\n\n");
        for (label, item) in orphans {
            out.push_str(&format!("- `{label}` at `{item}`\n"));
        }
    }

    out
}

/// Item cells for one requirement/direction, declared paths marked.
fn cells(scan: &Scan, label: &str, dir: Direction) -> Vec<String> {
    scan.citations
        .iter()
        .filter(|c: &&Citation| c.req_label == label && c.direction == dir)
        .map(|c| match c.origin {
            Origin::Declared => format!("`{}` _(declared)_", c.item_path),
            Origin::Annotation => format!("`{}`", c.item_path),
        })
        .collect()
}

enum Reason<'a> {
    Req(&'a str, String),
    Orphan(&'a str, &'a str),
}

fn status_reason(f: &Finding) -> Reason<'_> {
    match f {
        Finding::MissingSatisfier { req_label } => Reason::Req(req_label, "no satisfier".into()),
        Finding::MissingVerifier { req_label } => Reason::Req(req_label, "no verifier".into()),
        Finding::UnresolvedPath { req_label, item_path } => {
            Reason::Req(req_label, format!("unresolved `{item_path}`"))
        }
        Finding::SealBroken { req_label, item_path, .. } => {
            let what = if item_path == STATEMENT_MARKER {
                "statement drift".to_string()
            } else {
                format!("`{item_path}` drift")
            };
            Reason::Req(req_label, what)
        }
        Finding::DeadVerifier { req_label, item_path } => {
            Reason::Req(req_label, format!("dead verifier `{item_path}`"))
        }
        Finding::KindViolation { req_label, item_path } => {
            Reason::Req(req_label, format!("kind violation `{item_path}`"))
        }
        Finding::MisplacedAnnotation { label, item_path } => Reason::Orphan(label, item_path),
        Finding::SealModeMismatch { req_label, item_path } => {
            Reason::Req(req_label, format!("seal-mode mismatch `{item_path}`"))
        }
        Finding::SealModeOnExternal { req_label } => {
            Reason::Req(req_label, "seal-mode mismatch (all external)".to_string())
        }
        Finding::Uncovered { req_label, item_path } => {
            Reason::Req(req_label, format!("uncovered `{item_path}`"))
        }
        Finding::Unreconciled { req_label } => Reason::Req(req_label, "unreconciled".to_string()),
        Finding::OrphanAnnotation { label, item_path } => Reason::Orphan(label, item_path),
    }
}

fn kind_str(k: Kind) -> &'static str {
    match k {
        Kind::Functional => "functional",
        Kind::Invariant => "invariant",
    }
}

/// Keep statement text inside a single table cell.
fn escape(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use rubric_trace::check::{ItemFacts, ItemKind, Visibility};

    fn cite(label: &str, item: &str, dir: Direction, origin: Origin) -> Citation {
        Citation { req_label: label.into(), item_path: item.into(), direction: dir, origin }
    }

    fn facts(path: &str, is_test: bool, body: &str) -> ItemFacts {
        ItemFacts {
            path: path.into(),
            resolved: true,
            is_test,
            is_ignored: false,
            vis: Visibility::Private,
            kind: ItemKind::Fn,
            body: Some(body.into()),
            signature: None,
            evidence_seal: None,
        }
    }

    #[test]
    fn renders_row_per_requirement_with_status() {
        let manifest = rubric_trace::manifest::parse(
            "[req.TMR-1]\nkind=\"functional\"\nstatement=\"maj\"\n\
             [req.TMR-2]\nkind=\"invariant\"\nstatement=\"sym\"\n",
        )
        .unwrap();
        let scan = Scan {
            citations: vec![
                cite("TMR-1", "crate::vote", Direction::Satisfies, Origin::Annotation),
                cite("TMR-1", "crate::tests::t", Direction::Verifies, Origin::Annotation),
                cite("TMR-2", "crate::tests::sym", Direction::Verifies, Origin::Annotation),
            ],
            items: vec![
                facts("crate::vote", false, "x"),
                facts("crate::tests::t", true, "y"),
                facts("crate::tests::sym", true, "z"),
            ],
        };
        // Empty lock → everything reads as drifted.
        let report = check::check(&manifest, &Default::default(), &scan);
        let md = render(&manifest, &scan, &report, None);

        assert!(md.contains("| `TMR-1` | functional |"));
        // Invariant with no satisfier shows an em dash, not "missing".
        assert!(md.contains("| `TMR-2` | invariant | sym | — |"));
        assert!(md.contains("✗ "));
    }

    #[test]
    fn invariant_missing_verifier_is_flagged() {
        let manifest = rubric_trace::manifest::parse(
            "[req.X]\nkind=\"invariant\"\nstatement=\"s\"\n",
        )
        .unwrap();
        let scan = Scan::default();
        let report = check::check(&manifest, &Default::default(), &scan);
        let md = render(&manifest, &scan, &report, None);
        assert!(md.contains("**missing**")); // verifier column
    }
}
