// AUTO-GENERATED by `cargo rubric gen` — do not edit by hand.
// Re-run after editing rubric.toml; CI verifies this is up to date.
#![allow(non_camel_case_types, non_snake_case, dead_code)]

pub mod reqs {
    pub mod macro {
        pub struct block_scope_via_bind_at;
        pub struct emits_rustdoc_subsection;
        pub struct multi_path_annotations;
        pub struct no_std_compatible;
        pub struct silent_no_op_without_manifest;
        pub struct validates_path_at_compile_time;
        pub struct verifies_requirement_exists;
    }
}
