// AUTO-GENERATED by `cargo rubric gen` — do not edit by hand.
// Re-run after editing rubric.toml; CI verifies this is up to date.

#[allow(non_camel_case_types, non_snake_case, dead_code)]
pub mod reqs {
    pub mod codegen {
        /// # Requirement `codegen::handles_leaf_and_parent_collision`
        ///
        /// A label path that is both a terminal requirement and a parent of other requirements (e.g. `[req.x]` alongside `[req.x.y]`) renders both a marker struct and a nested module
        ///
        /// **ID:** `7a64713f7add927e`
        pub struct handles_leaf_and_parent_collision;
        /// # Requirement `codegen::renders_module_tree`
        ///
        /// Produce a nested `pub mod ... { pub struct <leaf>; }` tree that mirrors the manifest's label-path hierarchy
        ///
        /// **ID:** `9b476c0d207aaf95`
        pub struct renders_module_tree;
    }
    pub mod fnv {
        /// # Requirement `fnv::is_deterministic`
        ///
        /// Identical input bytes produce identical output across calls and across builds
        ///
        /// **ID:** `a4588613e2e64ed8`
        pub struct is_deterministic;
        /// # Requirement `fnv::matches_reference_vectors`
        ///
        /// FNV-1a 64-bit output matches the published reference vector for the input byte string `a`
        ///
        /// **ID:** `637d06f6929dc467`
        pub struct matches_reference_vectors;
    }
    pub mod hash {
        /// # Requirement `hash::body_scheme`
        ///
        /// Compute a deterministic FNV-1a hash over a function body's token stream with whitespace, line comments, block comments, and doc attributes stripped — the default `body:` scheme for seal values
        ///
        /// **ID:** `44675671ee6463b9`
        pub struct body_scheme;
    }
    pub mod lockfile {
        /// # Requirement `lockfile::parse_and_write`
        ///
        /// Parse and serialise rubric.lock entries keyed by (requirement label path, source item path); round-trip preserves formatting of a generated lockfile
        ///
        /// **ID:** `ebffe6169841388d`
        pub struct parse_and_write;
    }
    pub mod manifest {
        /// # Requirement `manifest::builds_from_entries`
        ///
        /// Group parsed TOML entries by section and materialise a typed Manifest record with requirement bodies
        ///
        /// **ID:** `3062b300e94a9d99`
        pub struct builds_from_entries;
        /// # Requirement `manifest::preserves_label_path`
        ///
        /// Map `[req.a.b.c]` to a Requirement whose label_path is [a, b, c], preserving ordering and depth
        ///
        /// **ID:** `b6e0a22d6978fa9e`
        pub struct preserves_label_path;
        /// # Requirement `manifest::requires_description`
        ///
        /// Reject a requirement section that omits the `description` key — every req must carry authoritative prose
        ///
        /// **ID:** `35043135f4ed39fd`
        pub struct requires_description;
    }
    pub mod resolver {
        /// # Requirement `resolver::tracks_item_path`
        ///
        /// Record the rustdoc-convention path of the enclosing fn or item for each annotation so seal entries in rubric.lock can key by item path in addition to requirement label
        ///
        /// **ID:** `184d9f03f373c28b`
        pub struct tracks_item_path;
    }
    pub mod toml_lite {
        /// # Requirement `toml_lite::parses_basic_strings`
        ///
        /// Decode basic string literals with the `\n`, `\t`, `\\`, `\"`, `\0` escape sequences supported by the TOML spec subset we need
        ///
        /// **ID:** `c6a12e81d595f55a`
        pub struct parses_basic_strings;
        /// # Requirement `toml_lite::parses_integers`
        ///
        /// Recognise decimal integer values, optionally with `_` digit separators
        ///
        /// **ID:** `683b99fa227ea1e8`
        pub struct parses_integers;
        /// # Requirement `toml_lite::parses_section_headers`
        ///
        /// Recognise `[a.b.c]` dotted section headers and attribute following key-value pairs to the nested path
        ///
        /// **ID:** `073a7b15587a4063`
        pub struct parses_section_headers;
        /// # Requirement `toml_lite::parses_string_arrays`
        ///
        /// Recognise arrays of basic strings, including arrays that span multiple source lines
        ///
        /// **ID:** `cd1d9eaf8f121571`
        pub struct parses_string_arrays;
        /// # Requirement `toml_lite::rejects_unterminated_strings`
        ///
        /// Surface a line-numbered error when a string literal is not closed before EOF or end-of-line
        ///
        /// **ID:** `aa495ec9d3d29b20`
        pub struct rejects_unterminated_strings;
    }
    pub mod walker {
        /// # Requirement `walker::comment_form_annotations`
        ///
        /// Recognise `// bind: <direction> = <path>, …` line-comment annotations so crates that can't consume the proc-macros (cycle, FFI) can still be tracked
        ///
        /// **ID:** `a2a860e342f06502`
        pub struct comment_form_annotations;
        /// # Requirement `walker::find_attribute_form`
        ///
        /// Recognise the `#[bind(...)]` attribute form, including path-prefixed invocations like `#[bind::bind(...)]`
        ///
        /// **ID:** `b73cafb8c9cda3f2`
        pub struct find_attribute_form;
        /// # Requirement `walker::find_function_like_form`
        ///
        /// Recognise the `bind_at!(...)` function-like form in expression scopes
        ///
        /// **ID:** `7fb264ec49d36c90`
        pub struct find_function_like_form;
        /// # Requirement `walker::ignore_strings_and_comments`
        ///
        /// Do not match bind-shaped patterns that occur inside string literals or comments
        ///
        /// **ID:** `59caa7b9876fe839`
        pub struct ignore_strings_and_comments;
        /// # Requirement `walker::multi_path_annotations`
        ///
        /// Accept comma-delimited path lists in a single annotation and emit one edge per path
        ///
        /// **ID:** `b117f6357e5f8323`
        pub struct multi_path_annotations;
    }
}
