//! Render the marker module for a manifest.
//!
//! Each requirement at label path `[a, b, c]` becomes
//! `crate::reqs::a::b::c` (modules for non-leaf parts, a unit
//! struct for the leaf). Developers reference these paths in `#[bind(...)]`
//! / `bind!(...)`, so name resolution catches typos.

use crate::manifest::{Manifest, ReqId, Requirement};

const HEADER: &str = "\
// AUTO-GENERATED by `cargo rubric gen` — do not edit by hand.
// Re-run after editing rubric.toml; CI verifies this is up to date.
";

// satisfies: codegen::renders_module_tree, codegen::handles_leaf_and_parent_collision
pub fn render(manifest: &Manifest) -> String {
    let mut tree = ModNode::default();
    for req in &manifest.requirements {
        tree.insert(&req.label_path, req);
    }
    let mut out = String::new();
    out.push_str(HEADER);
    // Outer attribute form so this module renders correctly whether the
    // file is `mod`-included or produced inline from a macro expansion.
    out.push_str("\n#[allow(non_camel_case_types, non_snake_case, dead_code)]\npub mod reqs {\n");
    tree.render(&mut out, 1, &[]);
    out.push_str("}\n");
    out
}

#[derive(Default)]
struct ModNode {
    children: Vec<(String, ModNode)>,
    leaf: Option<Requirement>,
}

impl ModNode {
    fn insert(&mut self, path: &[String], req: &Requirement) {
        let Some((head, tail)) = path.split_first() else {
            self.leaf = Some(req.clone());
            return;
        };
        for (name, child) in &mut self.children {
            if name == head {
                child.insert(tail, req);
                return;
            }
        }
        let mut child = ModNode::default();
        child.insert(tail, req);
        self.children.push((head.clone(), child));
    }

    fn render(&self, out: &mut String, depth: usize, path: &[&str]) {
        let mut kids: Vec<&(String, ModNode)> = self.children.iter().collect();
        kids.sort_by(|a, b| a.0.cmp(&b.0));
        for (name, child) in kids {
            let mut child_path: Vec<&str> = path.to_vec();
            child_path.push(name);
            if child.children.is_empty() {
                if let Some(req) = &child.leaf {
                    render_doc_struct(out, depth, name, req);
                }
            } else {
                indent(out, depth);
                out.push_str(&format!("pub mod {} {{\n", name));
                if let Some(req) = &child.leaf {
                    render_doc_struct(out, depth + 1, name, req);
                }
                child.render(out, depth + 1, &child_path);
                indent(out, depth);
                out.push_str("}\n");
            }
        }
    }
}

/// Emit a documented marker struct. Rendered doc becomes the requirement
/// page in `cargo doc` output and is the target of cross-links emitted by
/// the `#[bind(...)]` macro and the matrix.
fn render_doc_struct(out: &mut String, depth: usize, name: &str, req: &Requirement) {
    let id: ReqId = req.id();
    let label = req.label();
    indent(out, depth);
    out.push_str(&format!("/// # Requirement `{}`\n", label));
    indent(out, depth);
    out.push_str("///\n");
    indent(out, depth);
    out.push_str(&format!("/// {}\n", escape_doc_line(&req.description)));
    indent(out, depth);
    out.push_str("///\n");
    indent(out, depth);
    out.push_str(&format!("/// **ID:** `{}`\n", id));
    if !req.satisfied_by.is_empty() {
        indent(out, depth);
        out.push_str("///\n");
        indent(out, depth);
        out.push_str("/// **Satisfied by (declared):**\n");
        for p in &req.satisfied_by {
            indent(out, depth);
            out.push_str(&format!("/// - `{}`\n", p));
        }
    }
    if !req.verified_by.is_empty() {
        indent(out, depth);
        out.push_str("///\n");
        indent(out, depth);
        out.push_str("/// **Verified by (declared):**\n");
        for p in &req.verified_by {
            indent(out, depth);
            out.push_str(&format!("/// - `{}`\n", p));
        }
    }
    indent(out, depth);
    out.push_str(&format!("pub struct {};\n", name));
}

/// Line-escape — strip newlines (rustdoc treats /// ... lines individually)
/// and avoid closing a markdown code span unexpectedly. Keeps things dumb
/// for v0; richer manifest prose can use the optional `doc` backlink.
fn escape_doc_line(s: &str) -> String {
    s.replace('\n', " ")
}

fn indent(out: &mut String, depth: usize) {
    for _ in 0..depth { out.push_str("    "); }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::Manifest;

    #[test]
    #[rubric::verifies(crate::reqs::codegen::renders_module_tree)]
    fn renders_two_leaves_in_one_module() {
        let m = Manifest::parse(r#"
[meta]
version = 1
[req.parser.header_magic]
description = "x"
[req.parser.rejects_truncated]
description = "x"
"#).unwrap();
        let s = render(&m);
        assert!(s.contains("pub mod parser {"), "got: {}", s);
        assert!(s.contains("pub struct header_magic;"), "got: {}", s);
        assert!(s.contains("pub struct rejects_truncated;"), "got: {}", s);
    }

    #[test]
    #[rubric::verifies(crate::reqs::codegen::handles_leaf_and_parent_collision)]
    fn handles_non_leaf_with_leaf_collision() {
        // [req.x] AND [req.x.y] — `x` is both a leaf and a parent.
        let m = Manifest::parse(r#"
[meta]
version = 1
[req.x]
description = "outer"
[req.x.y]
description = "inner"
"#).unwrap();
        let s = render(&m);
        assert!(s.contains("pub mod x {"));
        assert!(s.contains("pub struct x;"));
        assert!(s.contains("pub struct y;"));
    }
}
